# Використовуємо образ Python
FROM python:3.10-slim

# Встановлюємо робочу директорію всередені нашого контейнера
WORKDIR /app

# Копіюємо залежності якщо вони необхідні
COPY requirements.txt .

# Встановлюємо необхідні залежності
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо всі файли проекту в контейнер
COPY app.py .

# Команда яку буде виконано при запуску контейнера
CMD ["python", "app.py"]